### ISSUE TITLE
Convert from Krutidev Devanagari Font

### ISSUE THREAD

**Issue by willi-mueller** [Grantha-Mandir/sanskrit-conversion#6]

**Comment by bhushank** [comment]
Added this enhancement. Have not tested on KrutiDev documents.

**Comment by willi-mueller** [comment]
@bhushank I'd suggest that we first test it on Krutidev documents before we close this ticket :-)

See a18c6c7.

**Comment by willi-mueller** [comment]
Currently, we have no file to convert in Krutidev
