### ISSUE TITLE
Convert from Devanagari New

### ISSUE THREAD

**Issue by willi-mueller** [Grantha-Mandir/sanskrit-conversion#9]
As a user I can convert docx files from Devanagari New to a Unicode Devanagari font like Sanskrit 2003. This conversion only replaces text blocks which are encoded with Devanagari New because the present documents have both Devanagari as well as Roman characters for English or Lithuanian.

**Comment by bhushank** [comment]
Added this today. In the dropdown you can see RM Devanagiri, this is Devanagiri New.
